param(
  [string]$Repo = "ZZZZzzzzac/PbDH_Sheet"
)

$ErrorActionPreference = "Stop"

function Find-Gh {
  $cmd = Get-Command gh -ErrorAction SilentlyContinue
  if ($cmd) {
    return $cmd.Source
  }

  $workspaceGh = Join-Path $PSScriptRoot "..\tools\gh\bin\gh.exe"
  if (Test-Path $workspaceGh) {
    return (Resolve-Path $workspaceGh).Path
  }

  $programFilesGh = "C:\Program Files\GitHub CLI\gh.exe"
  if (Test-Path $programFilesGh) {
    return $programFilesGh
  }

  $programFilesX86Gh = "C:\Program Files (x86)\GitHub CLI\gh.exe"
  if (Test-Path $programFilesX86Gh) {
    return $programFilesX86Gh
  }

  throw "GitHub CLI was not found. Install it first, then run this script again."
}

function New-TempBodyFile([string]$Body) {
  $path = Join-Path ([System.IO.Path]::GetTempPath()) ("pbdh-issue-" + [System.Guid]::NewGuid().ToString("N") + ".md")
  Set-Content -LiteralPath $path -Value $Body -Encoding UTF8
  return $path
}

function Create-Issue([string]$Title, [string]$Body) {
  $bodyFile = New-TempBodyFile $Body
  try {
    & $Gh issue create --repo $Repo --title $Title --body-file $bodyFile --label "enhancement" --label "needs-triage"
  }
  finally {
    Remove-Item -LiteralPath $bodyFile -Force -ErrorAction SilentlyContinue
  }
}

$Gh = Find-Gh
& $Gh auth status --hostname github.com

$disclaimer = "> *This was generated by AI during triage.*"

$prdBody = @"
$disclaimer

## Problem Statement

Authors can currently choose page, section, and module order, but actual Sheet Tool layout is mostly fixed by the Base Framework. Every section renders through one automatic grid, so Authors cannot declare rows, columns, column widths, module slot sizes, spacing, or basic layout styling in the System Package.

## Solution

Extend Flow Layout so Authors can declare layout structure and sizing in the System Package while keeping Sheet Renderer as the owner of layout rendering. Preserve existing `section.modules` packages and add `section.rows -> columns -> modules`.

## User Stories

1. As an Author, I want existing `section.modules` packages to keep working, so that old System Packages remain valid.
2. As an Author, I want to group Sheet Modules into rows and columns, so that pages can express intentional structure.
3. As an Author, I want column widths and minimum widths, so that modules can have different visual weight and wrap on mobile.
4. As an Author, I want gap, margin, padding, background, border, radius, and alignment fields, so that System Packages can control density and grouping.
5. As a Player, I want customized layouts to remain responsive, so that the Sheet Tool works on desktop and mobile.

## Implementation Decisions

- Sheet Renderer remains responsible for Flow Layout.
- Support legacy `section.modules` and rich `section.rows[].columns[].modules`.
- Module placements can be strings or objects with `ID` and layout style.
- Layout styling is safe box styling, not arbitrary global CSS.
- Character Data remains keyed by module ID.

## Testing Decisions

- Test schema validation for legacy and rich Flow Layout.
- Test nested missing module references.
- Test renderer output for rows, columns, and module slots.
- Keep existing module interaction tests passing.

## Out of Scope

- Drag-and-drop layout editor.
- Overlay Layout.
- Arbitrary page-level Author CSS.
- Moving Sheet Module state into layout nodes.
"@

$issue1Body = @"
$disclaimer

## What to build

Allow System Packages to describe Flow Layout with rows, columns, module placements, and basic layout style fields, while preserving the legacy `section.modules` shape.

## Acceptance criteria

- [ ] Existing System Packages using `section.modules` still validate.
- [ ] New System Packages can use `section.rows[].columns[].modules`.
- [ ] Missing module references inside nested row/column placements are reported as validation errors.
- [ ] A section must declare either legacy `modules` or rich `rows`.
- [ ] Types are exported for row, column, placement, and layout style shapes.

## Blocked by

None - can start immediately.
"@

$issue2Body = @"
$disclaimer

## What to build

Update Sheet Renderer so it renders rich Flow Layout rows and columns, applies declared sizes/styles, and falls back to the existing automatic grid for legacy sections.

## Acceptance criteria

- [ ] Legacy sections still render with the current responsive module grid.
- [ ] Rich sections render rows and columns in declared order.
- [ ] Column width, min width, gap, padding, margin, alignment, and basic box styles are applied.
- [ ] Sheet Modules still receive the same module config and System Package props.
- [ ] Existing module behavior tests still pass.

## Blocked by

Flow Layout schema and validation issue.
"@

$issue3Body = @"
$disclaimer

## What to build

Update a demo System Package and tests so Authors and future agents can see the richer Flow Layout shape in use.

## Acceptance criteria

- [ ] Demo pages include at least two rows and multiple columns with different widths.
- [ ] Tests assert that rich layout containers render and wrap module content correctly.
- [ ] Tests assert that nested missing module references produce validation errors.
- [ ] The docs identify this as Flow Layout, not Overlay Layout.

## Blocked by

Flow Layout schema and renderer issues.
"@

Create-Issue "PRD: Customizable Flow Layout for System Packages" $prdBody
Create-Issue "Add rich Flow Layout schema and validation" $issue1Body
Create-Issue "Render row and column Flow Layout in Sheet Renderer" $issue2Body
Create-Issue "Add demo package and tests for customizable Flow Layout" $issue3Body
