// Generated from the runtime Zod contracts. Do not edit.
// Package scripts export: module.exports = async function (input) { ... }

export type ValidationInput = { "characterData": { "kind": "pbdh-character-data"; "schemaVersion": "0.1.0"; "systemPackage": { "id": string; "version": string; }; "character": { "id": string; "values": { [key: string]: string | { [key: string]: boolean; } | { "current": number; "max": number | null; } | { "kind": "player-image"; "imageId": string; }; }; }; "cards": { "instances": Array<{ "instanceId": string; "tableModuleId": string; "definitionRef"?: { "type": "resourceLibrary"; "libraryId": string; "entryId": string; } | { "type": "compositeResource"; "compositeResourceId": string; }; "libraryId"?: string; "definitionId"?: string; "state": string; "xPct": number; "yPct": number; "zIndex": number; "face": "front" | "back"; "rotation": number; "scale": number; "indicators": Array<{ "indicatorId": string; "colorIndex": number; "value": number; }> | { [key: string]: number; }; "tokenCount"?: number; }>; }; "compositeResources": { [key: string]: { "ID": string; "composerModuleId": string; "fields": { [key: string]: string; }; }; }; "resourceSelections": { [key: string]: { "libraryId": string; "entryIds": Array<string>; }; }; "playerImages": { [key: string]: { "id": string; "name"?: string; "mimeType": string; "dataUrl": string; }; }; "updatedAt": string; }; "resourceLibraries": Array<{ "ID": string; "名称": string; "路径": string; "fields": Array<{ "key": string; "label": string; "visible": boolean; "filterable": boolean; "sortable": boolean; "searchable": boolean; "width"?: "compact" | "normal" | "wide" | "fill"; }>; "entries": Array<{ "ID": string; "aliases"?: Array<string>; "fields": { [key: string]: string; }; }>; }>; "cardState": { "instances": Array<{ "instanceId": string; "tableModuleId": string; "definitionRef"?: { "type": "resourceLibrary"; "libraryId": string; "entryId": string; } | { "type": "compositeResource"; "compositeResourceId": string; }; "libraryId"?: string; "definitionId"?: string; "state": string; "xPct": number; "yPct": number; "zIndex": number; "face": "front" | "back"; "rotation": number; "scale": number; "indicators": Array<{ "indicatorId": string; "colorIndex": number; "value": number; }> | { [key: string]: number; }; "tokenCount"?: number; }>; }; "packageMetadata": { "id": string; "version": string; }; };

export type ValidationOutput = Array<{ "level": "error" | "warning" | "info"; "text": string; "path"?: string; "code"?: string; }> | { "issues": Array<{ "level": "error" | "warning" | "info"; "text": string; "path"?: string; "code"?: string; }>; };

export type ResourceAdapterImportInput = { "document": unknown; "fileName": string; "assets": Array<{ "path": string; "bytes": Uint8Array; }>; "resourceLibraries": Array<{ "ID": string; "名称": string; "路径": string; "fields": Array<{ "key": string; "label": string; "visible": boolean; "filterable": boolean; "sortable": boolean; "searchable": boolean; "width"?: "compact" | "normal" | "wide" | "fill"; }>; "entries": Array<{ "ID": string; "aliases"?: Array<string>; "fields": { [key: string]: string; }; }>; }>; };

export type ResourceAdapterImportOutput = { "name": string; "version"?: string; "resourceLibraries": Array<{ "ID"?: string; "名称": string; "entries": Array<{ [key: string]: unknown; }>; }>; "retainedAssets"?: Array<{ "sourcePath": string; "targetPath": string; }>; "diagnostics"?: Array<{ "level": "error" | "warning"; "code": string; "text": string; "path"?: string; }>; "counts": { "sourceEntries": number; "convertedEntries": number; "skippedEntries": number; "convertedFields": number; "skippedFields": number; "boundImages": number; "orphanImages": number; }; };

export type CharacterAdapterImportInput = { "document": unknown; "fileName": string; "resourceLibraries": Array<{ "ID": string; "名称": string; "路径": string; "fields": Array<{ "key": string; "label": string; "visible": boolean; "filterable": boolean; "sortable": boolean; "searchable": boolean; "width"?: "compact" | "normal" | "wide" | "fill"; }>; "entries": Array<{ "ID": string; "aliases"?: Array<string>; "fields": { [key: string]: string; }; }>; }>; };

export type CharacterAdapterImportOutput = { "values": { [key: string]: unknown; }; "cards"?: Array<{ "tableModuleId": string; "state": string; "libraryId": string; "entryId": string; }>; "images"?: Array<{ "moduleId": string; "name"?: string; "dataUrl": string; }>; "suggestedSaveName"?: string; "skippedFields"?: number; "skippedCards"?: number; "skippedImages"?: number; "diagnostics"?: Array<{ "level": "error" | "warning"; "code": string; "text": string; "path"?: string; }>; };

export type CharacterAdapterExportInput = { "adapterId": string; "characterData": { "kind": "pbdh-character-data"; "schemaVersion": "0.1.0"; "systemPackage": { "id": string; "version": string; }; "character": { "id": string; "values": { [key: string]: string | { [key: string]: boolean; } | { "current": number; "max": number | null; } | { "kind": "player-image"; "imageId": string; }; }; }; "cards": { "instances": Array<{ "instanceId": string; "tableModuleId": string; "definitionRef"?: { "type": "resourceLibrary"; "libraryId": string; "entryId": string; } | { "type": "compositeResource"; "compositeResourceId": string; }; "libraryId"?: string; "definitionId"?: string; "state": string; "xPct": number; "yPct": number; "zIndex": number; "face": "front" | "back"; "rotation": number; "scale": number; "indicators": Array<{ "indicatorId": string; "colorIndex": number; "value": number; }> | { [key: string]: number; }; "tokenCount"?: number; }>; }; "compositeResources": { [key: string]: { "ID": string; "composerModuleId": string; "fields": { [key: string]: string; }; }; }; "resourceSelections": { [key: string]: { "libraryId": string; "entryIds": Array<string>; }; }; "playerImages": { [key: string]: { "id": string; "name"?: string; "mimeType": string; "dataUrl": string; }; }; "updatedAt": string; }; "resourceLibraries": Array<{ "ID": string; "名称": string; "路径": string; "fields": Array<{ "key": string; "label": string; "visible": boolean; "filterable": boolean; "sortable": boolean; "searchable": boolean; "width"?: "compact" | "normal" | "wide" | "fill"; }>; "entries": Array<{ "ID": string; "aliases"?: Array<string>; "fields": { [key: string]: string; }; }>; }>; };

export type CharacterAdapterExportOutput = { "document": { [key: string]: unknown; }; "diagnostics"?: Array<{ "level": "error" | "warning"; "code": string; "text": string; "path"?: string; }>; "exportedFields"?: number; "skippedFields"?: number; "exportedCards"?: number; "skippedCards"?: number; "exportedImages"?: number; "skippedImages"?: number; };

export type PackageScript<TInput, TOutput> = (input: Readonly<TInput>) => TOutput | Promise<TOutput>;
